### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by lapastillaroja** [JSAURAJ/AlmacenesElChollo#1]
@JSAURAJ teneis el diagrama de clases hecho?

**Comment by JSAURAJ** [comment]
Si, algo tenemos.

**Comment by lapastillaroja** [comment]
Sube una captura de pantalla y lo vamos mirando

**Comment by JSAURAJ** [comment]
ya lo tienes todo en el último commit

**Comment by lapastillaroja** [comment]
Ok. Este commit? 58a879039db283a7845c6233a938de0326d36401

**Comment by JSAURAJ** [comment]
El mismo, cuando puedas me conectó, estoy con el MV.

**Comment by lapastillaroja** [comment]
Preguntas sobre el diagrama

- Producto: Que diferencia existe entre el `idGenerio` y el `idUnico`?
- Producto: Es necesario exponer el metodo `setIdUnico`?
- Tecnologia: `garantia` es un `int`. Pero esa cifra que indica? Segundos? Dias?
- Alimentacion: Pq separais dia, mes y anho? 
- Pedido: Es necesario exponer el metodo `setIdPedido`?
- Pedido: `setProducto` que tipo de argumento recibe?

**Comment by lapastillaroja** [comment]
Otra pregunta

- Donde se refleja esto? `El precio de la cesta será la suma del precio de todos los productos que lo componen.`

**Comment by JSAURAJ** [comment]
- Queremos que cada producto tengo su id único, pero también un id común con productos de su rama, por ejemplo: Todos los productos de jamones tienen el id común 0001, pero como cada jamón es único se le tiene que identificar por su id único para que pueda ser trazable, habrá mil formas de hacerlo digo yo....

- No es necesario, ya que la idea es que se autogenere al instanciar un producto, pero el visual paradigm crea los geters y los seters, no es definitivo y hay que borrar muchas cosas.

- Lo de garantía ni idea, no lo he puesto y no se . Tampoco lo que indica...

- Habrá sido al copiar, es una fecha y listo, un date (desconozco en java)

- Igual que producto, hay que quitarlo, se autogenera solo, el diagrama no es ni mucho menos definitivo

- Esta te la contesto mañana cuando lo vea bien. 

- No está terminado, lo que había pensado es crear una interfaz de calcular precio, aunque estamos un poco liados, mañana nos dices posibilidades.


Voy a dormir hasta las 10, a las 10 me conecto y me pongo como loco a esto, queremos terminarlo en max 3 días


Buenas noches!

**Comment by norber88** [comment]
* Alimentacion: Pq separais dia, mes y anho?
Estuve viendo como tratar las fechas en java y me fijé en que no hay un tipo de datos que sea "date" por ejemplo. Pensé en ponerlo como String, pero para operar con la fecha del sistema y demás no hallé la forma de hacerlo, encontré que muchos la ponían como int por separado y luego usaban un método de la clase object para dale formato de fecha. Por eso lo puse así, pero vamos que ni idea de si  hay otras formas de hacerlo y mejores. ¿Cómo se podría hacer?

**Comment by lapastillaroja** [comment]
@norber88 @JSAURAJ 
> Estuve viendo como tratar las fechas en java y me fijé en que no hay un tipo de datos que sea "date" por ejemplo.

Si que hay. Mira aqui: http://docs.oracle.com/javase/7/docs/api/java/sql/Date.html

**Comment by lapastillaroja** [comment]
Ok este es el feedback despues de hablar con mi hermano con Skype

- idUnico NO puede ser static. Sobre la forma de generarlo, aqui: #2 
- Recordad el uso de `@Override` al definir el metodo `getPrecio` en la cesta
- Un cliente normal debe tener `getDescuento()` para poder calcular el precio del pedido sin problemas. En este caso el valor seria `0`
- Fechas: mejor usar internamente la clase `util.Date` de java. Los constructores con dia, mes y anyo separados, sin problema.

**Comment by JSAURAJ** [comment]
@lapastillaroja , @norber88 
> -idUnico NO puede ser static. Sobre la forma de generarlo, aqui: #2

ya está cambiado, revísalo
> -Recordad el uso de @Override al definir el metodo getPrecio en la cesta

Esto ya estaba hecho, no lo miraste bien
> -Un cliente normal debe tener getDescuento() para poder calcular el precio del pedido sin problemas. En este caso el valor seria 0

Ya está cambiado, aunque el método `getDescuento` habría que ponerlo en la clase `Pedido` no?
> -Fechas: mejor usar internamente la clase util.Date de java. Los constructores con dia, mes y anyo separados, sin problema.

Tambien está modificado

**Comment by JSAURAJ** [comment]
Que le follen al diagrama.
